// AUTO-GENERATED — do not edit this file directly.
// Source of truth: packages/engine-core/src/client.d.ts
// Generated by: packages/engine-core/scripts/copy-client-dts.mjs  (run as part of `pnpm build`)
//


declare module '@portfolio-engine:config' {
  export const config: import('@portfolio-engine/engine-core').ResolvedConfig;
}

declare module '@portfolio-engine:context' {
  export const context: import('@portfolio-engine/engine-core').BuildContext;
}

declare module '@portfolio-engine:routes' {
  export const routes: import('@portfolio-engine/engine-core').RouteRegistry;
}

declare module '@portfolio-engine:overrides' {
  export const overrides: import('@portfolio-engine/engine-core').OverrideMap;
}

// Per-surface override modules. Each exports the consumer's override component,
// or null when no override is configured for that surface.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type OverrideComponent = ((...args: any[]) => any) | null;

declare module '@portfolio-engine:override/Hero' {
  const Override: OverrideComponent;
  export default Override;
}
declare module '@portfolio-engine:override/FeaturedWriting' {
  const Override: OverrideComponent;
  export default Override;
}
declare module '@portfolio-engine:override/TestimonialSection' {
  const Override: OverrideComponent;
  export default Override;
}
declare module '@portfolio-engine:override/CollaborationSection' {
  const Override: OverrideComponent;
  export default Override;
}
declare module '@portfolio-engine:override/Footer' {
  const Override: OverrideComponent;
  export default Override;
}
