import fs from 'node:fs';
import path from 'node:path';
const ROOT = path.resolve('/mnt/data/portfolio_engine_v4_report_pack');
const SRC = path.join(ROOT, 'source');
const REPORT = path.join(ROOT, 'report');
function esc(s){ return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;'); }
function inline(s){ return esc(s).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>'); }
function mdToHtml(md){
  const lines = md.split(/\r?\n/); let out=[]; let inCode=false; let code=[]; let inUl=false;
  function closeUl(){ if(inUl){ out.push('</ul>'); inUl=false; } }
  for(const line of lines){
    if(line.startsWith('```')){ if(!inCode){ closeUl(); inCode=true; code=[]; } else { out.push('<pre><code>'+esc(code.join('\n'))+'</code></pre>'); inCode=false; } continue; }
    if(inCode){ code.push(line); continue; }
    if(!line.trim()){ closeUl(); continue; }
    if(line.startsWith('# ')){ closeUl(); out.push('<h1>'+inline(line.slice(2))+'</h1>'); }
    else if(line.startsWith('## ')){ closeUl(); out.push('<h2>'+inline(line.slice(3))+'</h2>'); }
    else if(line.startsWith('### ')){ closeUl(); out.push('<h3>'+inline(line.slice(4))+'</h3>'); }
    else if(line.startsWith('#### ')){ closeUl(); out.push('<h4>'+inline(line.slice(5))+'</h4>'); }
    else if(line.startsWith('- ')){ if(!inUl){ out.push('<ul>'); inUl=true; } out.push('<li>'+inline(line.slice(2))+'</li>'); }
    else if(line.startsWith('> ')){ closeUl(); out.push('<blockquote>'+inline(line.slice(2))+'</blockquote>'); }
    else { closeUl(); out.push('<p>'+inline(line)+'</p>'); }
  }
  closeUl(); return out.join('\n');
}
function depSvg(){ return `<svg class="depgraph" viewBox="0 0 920 430" role="img" aria-label="Dependency graph"><defs><marker id="arrow" markerWidth="10" markerHeight="10" refX="9" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#334155"></path></marker></defs><rect x="50" y="50" width="170" height="70" rx="16" class="node required"></rect><text x="135" y="82" text-anchor="middle" class="node-title">schema</text><text x="135" y="104" text-anchor="middle" class="node-sub">required</text><rect x="310" y="50" width="190" height="70" rx="16" class="node required"></rect><text x="405" y="82" text-anchor="middle" class="node-title">engine-core</text><text x="405" y="104" text-anchor="middle" class="node-sub">required</text><rect x="600" y="50" width="220" height="70" rx="16" class="node required"></rect><text x="710" y="82" text-anchor="middle" class="node-title">editorial-theme</text><text x="710" y="104" text-anchor="middle" class="node-sub">required</text><rect x="600" y="185" width="220" height="70" rx="16" class="node consumer"></rect><text x="710" y="217" text-anchor="middle" class="node-title">consumer site</text><text x="710" y="239" text-anchor="middle" class="node-sub">agreni / jordan</text><rect x="300" y="300" width="230" height="70" rx="16" class="node optional"></rect><text x="415" y="332" text-anchor="middle" class="node-title">admin-tools</text><text x="415" y="354" text-anchor="middle" class="node-sub">optional UI</text><rect x="600" y="300" width="250" height="70" rx="16" class="node optional"></rect><text x="725" y="332" text-anchor="middle" class="node-title">workflow-kit</text><text x="725" y="354" text-anchor="middle" class="node-sub">optional Python/MCP</text><line x1="220" y1="85" x2="310" y2="85" class="edge"></line><line x1="500" y1="85" x2="600" y2="85" class="edge"></line><line x1="710" y1="120" x2="710" y2="185" class="edge"></line><line x1="610" y1="235" x2="500" y2="300" class="edge optional-edge"></line><line x1="725" y1="300" x2="725" y2="255" class="edge optional-edge"></line><text x="460" y="160" text-anchor="middle" class="mvp-star">★ MVP after required runtime + demo + CI + docs</text></svg>`; }
function listFiles(dir){ let out=[]; for(const name of fs.readdirSync(dir)){ const p=path.join(dir,name); const st=fs.statSync(p); if(st.isDirectory()) out=out.concat(listFiles(p)); else out.push(p); } return out; }
const model = JSON.parse(fs.readFileSync(path.join(SRC,'project_model.json'),'utf8'));
const sections = Object.fromEntries(fs.readdirSync(path.join(SRC,'sections')).filter(f=>f.endsWith('.md')).sort().map(f=>[path.basename(f,'.md'), fs.readFileSync(path.join(SRC,'sections',f),'utf8')]));
const epicFiles = fs.readdirSync(path.join(SRC,'epics')).filter(f=>f.endsWith('.md')).sort();
const cards = model.packages.map(p=>`<div class="package-card ${p.mvp?'required':'optional'}"><div class="package-kind">${esc(p.kind)}</div><h3>${esc(p.name)}</h3><p><strong>Language:</strong> ${esc(p.language)}</p><p>${esc(p.purpose)}</p><p class="muted"><strong>Depends on:</strong> ${esc(p.dependsOn.length?p.dependsOn.join(', '):'none')}</p></div>`).join('\n');
const epicHtml = epicFiles.map(f=>{ const md=fs.readFileSync(path.join(SRC,'epics',f),'utf8'); const title=md.split(/\r?\n/)[0].replace(/^# /,''); const mvp=md.includes('★ Required')||md.includes('★ Reference'); return `<details class="epic-card ${mvp?'mvp':'post'}" open><summary>${esc(title)} <span>${mvp?'★ MVP-related':'post-MVP / support'}</span></summary><div class="source-link">Source: <code>source/epics/${esc(f)}</code></div>${mdToHtml(md)}</details>`; }).join('\n');
const sourceList = listFiles(SRC).sort().map(p=>`<li><code>${esc(path.relative(ROOT,p))}</code></li>`).join('\n');
const body = `<section class="hero"><div class="eyebrow">Source-driven architecture report</div><h1>${esc(model.title)}</h1><p>${esc(model.summary||'')}</p><div class="hero-badges"><span>Required Astro/npm runtime</span><span>Optional Python/MCP workflow-kit</span><span>Optional admin UI</span><span>★ MVP marker</span></div></section><section id="goals" class="panel">${mdToHtml(sections['01_big_picture_goals'])}</section><section id="packages" class="panel"><h1>Required vs Optional Packages</h1><p>The required runtime packages are schema, engine-core, and editorial-theme. The optional packages are admin-tools and workflow-kit.</p><div class="package-grid">${cards}</div></section><section id="graph" class="panel"><h1>Dependency Graph and MVP Marker</h1>${depSvg()}</section><section id="upstream" class="panel">${mdToHtml(sections['03_upstream_layout'])}</section><section id="consumer" class="panel">${mdToHtml(sections['04_consumer_layout'])}</section><section id="audit" class="panel">${mdToHtml(sections['02_current_vs_target'])}</section><section id="roadmap" class="panel">${mdToHtml(sections['05_mvp_roadmap'])}</section><section id="gap" class="panel">${mdToHtml(sections['06_gap_plan']||'')}</section><section id="epics" class="panel"><h1>Epics and Atomic Tickets</h1><p>Generated from <code>source/epics/*.md</code>. Do not blindly create all issues. Reconcile against the live GitHub board first.</p><input id="epicSearch" class="search" oninput="filterEpics()" placeholder="Filter epics/tickets...">${epicHtml}</section><section id="sources" class="panel"><h1>Canonical Source Files</h1><p>The report is generated from these files. Edit <code>source/</code>, then rerun <code>node scripts/build_report.mjs</code>.</p><ul>${sourceList}</ul></section>`;
const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Portfolio Engine v4 Audit</title><link rel="stylesheet" href="assets/styles.css"></head><body><div class="app"><aside class="sidebar"><div class="brand">Portfolio Engine<br><span>v4 audit pack</span></div><nav><a href="#goals">Goals</a><a href="#packages">Packages</a><a href="#graph">Dependency graph</a><a href="#upstream">Upstream repo</a><a href="#consumer">Consumer repo</a><a href="#audit">Current vs target</a><a href="#roadmap">MVP roadmap</a><a href="#epics">Epics & tickets</a><a href="#sources">Source files</a></nav></aside><main>${body}</main></div><script>function filterEpics(){const q=document.getElementById('epicSearch').value.toLowerCase();document.querySelectorAll('.epic-card').forEach(c=>{c.style.display=c.innerText.toLowerCase().includes(q)?'':'none';});}</script></body></html>`;
fs.writeFileSync(path.join(REPORT,'index.html'), html);
